### ISSUE TITLE
Instructions for install in Readme

### ISSUE THREAD

**Issue by DoctorMikeReddy** [emfcamp/Mk4-micropython-board#1]
On my machine - Windows 8.1 the following command gave me an error:

git submodule add git@github.com:emfcamp/Mk4-micropython-board.git

It should be:

git submodule add git@github.com:emfcamp/Mk4-micropython-board.git ports/ti

However, this fails on Windows, with a rights issue

**Comment by mstratford** [comment]
I had an issue with rights, I just changed the git@.... to https://github.com/emfcamp....

**Comment by DoctorMikeReddy** [comment]
I did that too, but had to clone into a separate repo, then move the files. Of course, compiling on a Win machine is the next hurdle…
