### ISSUE TITLE
UART4 not enabled by default

### ISSUE THREAD

**Issue by Molive-0** [emfcamp/Mk4-micropython-board#2]
UART port 4 is not loaded as a driver by default. This means that micropython cannot access it (returns OSerror 19: ENODEV), and the top UART pins cannot be used.

This is one of the major features of the badge but just appears to be unusable.

> --- import machine
--- machine.UART(2, 115200)
<machine_uart.60057380> id=2 baudrate=115200 bits=8 parity=0 stop=1 flow=0x0 mode=0 timeout=1000 read_buf_len=64
--- machine.UART(4, 115200)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: 19
---

**Comment by mgsb** [comment]
The UART IDs in MP do not match the physical UART numbers. Use the symbolic names like UART.UART_EXTERNAL for the UART connected to Grove connectors and the header. These are defined in the CSV file in the boards directory.
